server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pfsense-syslog
    syslog:
      listen_address: 0.0.0.0:5140
      listen_protocol: udp
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: pfsense
