---
- name: Deploy AdGuard Home using Docker
  hosts: docker
  become: yes
  vars:

  tasks:
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ adguard_config_dir }}"
        - "{{ adguard_work_dir }}"

    - name: Deploy AdGuardHome.yaml configuration
      template:
        src: templates/AdGuardHome.yaml.j2
        dest: "{{ adguard_config_dir }}/AdGuardHome.yaml"
        mode: "0644"

    - name: Run AdGuard Home container
      community.docker.docker_container:
        name: "{{ adguard_container_name }}"
        image: "{{ adguard_image }}"
        restart_policy: always
        ports: "{{ adguard_ports }}"
        volumes:
          - "{{ adguard_config_dir }}:/opt/adguardhome/conf"
          - "{{ adguard_work_dir }}:/opt/adguardhome/work"
        state: started
