---
servers:
  vars:
    ansible_user: vagrant
    ansible_become: true
  hosts:
    docker:
      ansible_host: 192.168.56.10
      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/docker/virtualbox/private_key
    ntopng:
      ansible_host: 192.168.56.11
      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/ntopng/virtualbox/private_key

routers:
  hosts:
    pfsense:
      ansible_host: 192.168.56.254
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/pfsense/virtualbox/private_key

clients:
  vars:
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
    ansible_become: true
  hosts:
    student:
      ansible_host: 192.168.60.2
