---
- name: Deploy Loki, Promtail, and Grafana via Docker Compose
  hosts: docker
  become: yes

  tasks:
    # - name: Ensure Python Docker SDK is installed
    #   ansible.builtin.pip:
    #     name:
    #       - docker
    #       - requests==2.31.0
    #       - paramiko
    #     state: latest

    - name: Ensure loki directory exists
      ansible.builtin.file:
        path: "{{ loki_dir }}"
        state: directory
        mode: "0755"

    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items: "{{ files }}"

    - name: Bring up Loki stack with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ loki_dir }}"
        state: present
