---
- name: pfSense configuration
  hosts: routers
  gather_facts: no
  become: yes
  tasks:
    - name: Copy files to pfSense
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items: "{{ files }}"

    - name: Reboot pfSense
      shell: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: End play gracefully after reboot
      meta: end_play
